#Requires -RunAsAdministrator
<#
.SYNOPSIS
  Installs the ShelfPOS Supabase sync service on Windows.

.DESCRIPTION
  Run AFTER installing ShelfPOS via "ShelfPOS Setup*.exe" (double-click the setup yourself).
  Right-click this script -> Run with PowerShell as Administrator.

  1. Copies sync-service to Program Files
  2. Writes sync.env with Supabase credentials
  3. Registers and starts the "ShelfPOS Sync" Windows service

.PARAMETER SupabaseUrl
  e.g. https://xxxx.supabase.co

.PARAMETER SupabaseServiceKey
  Service role key (Project Settings -> API). NOT the anon key.

.PARAMETER StoreId
  store_a or store_b — stamped on every row pushed to Supabase.
#>
param(
  [string]$SupabaseUrl,
  [string]$SupabaseServiceKey,
  [string]$StoreId = 'store_a'
)

$ErrorActionPreference = 'Stop'
$BundleRoot = $PSScriptRoot
$ServiceName = 'ShelfPOSSync'
$InstallDir = Join-Path ${env:ProgramFiles} 'ShelfPOS\sync-service'
$SqlitePath = Join-Path $env:APPDATA 'shelfpos\shelf.db'

function Prompt-Required([string]$Label, [switch]$Secret) {
  if ($Secret) {
    $secure = Read-Host $Label -AsSecureString
    return [Runtime.InteropServices.Marshal]::PtrToStringAuto(
      [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    )
  }
  return Read-Host $Label
}

Write-Host ''
Write-Host '=== ShelfPOS sync service installer ===' -ForegroundColor Cyan
Write-Host '    (Install ShelfPOS app separately via ShelfPOS Setup*.exe first.)' -ForegroundColor DarkGray
Write-Host ''

if (-not $SupabaseUrl) {
  $SupabaseUrl = Prompt-Required 'Supabase URL (https://xxx.supabase.co)'
}
if (-not $SupabaseServiceKey) {
  $SupabaseServiceKey = Prompt-Required 'Supabase service role key' -Secret
}
$StoreId = ($StoreId).Trim()
if ($StoreId -notmatch '^store_[a-z0-9_]+$') {
  throw "Invalid StoreId: $StoreId (use store_a, store_b, etc.)"
}

$SyncSource = Join-Path $BundleRoot 'sync-service'
if (-not (Test-Path (Join-Path $SyncSource 'dist\index.js'))) {
  throw "sync-service bundle missing. Re-run npm run release:win on the build machine."
}

Write-Host "Installing sync service to $InstallDir" -ForegroundColor Yellow
if (Test-Path $InstallDir) {
  Stop-Service -Name $ServiceName -ErrorAction SilentlyContinue
  Start-Sleep -Seconds 1
  Remove-Item -Recurse -Force $InstallDir
}
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null

Copy-Item -Recurse -Force (Join-Path $SyncSource 'dist') (Join-Path $InstallDir 'dist')
Copy-Item -Recurse -Force (Join-Path $SyncSource 'node_modules') (Join-Path $InstallDir 'node_modules')
Copy-Item -Force (Join-Path $SyncSource 'package.json') $InstallDir
Copy-Item -Force (Join-Path $SyncSource 'node.exe') $InstallDir
Copy-Item -Recurse -Force (Join-Path $SyncSource 'scripts') (Join-Path $InstallDir 'scripts')

$SyncEnv = @"
# ShelfPOS sync service — auto-generated by Install-ShelfPOS.ps1
SUPABASE_URL=$SupabaseUrl
SUPABASE_SERVICE_KEY=$SupabaseServiceKey
SQLITE_PATH=$SqlitePath
"@
Set-Content -Path (Join-Path $InstallDir 'sync.env') -Value $SyncEnv -Encoding UTF8

$dbDir = Split-Path $SqlitePath -Parent
if (-not (Test-Path $dbDir)) {
  New-Item -ItemType Directory -Path $dbDir -Force | Out-Null
}
if (Test-Path $SqlitePath) {
  Write-Host "Setting sync_store_id=$StoreId in SQLite" -ForegroundColor Yellow
  & (Join-Path $InstallDir 'node.exe') `
    (Join-Path $InstallDir 'scripts\set-store-id.cjs') `
    $SqlitePath $StoreId
} else {
  Write-Host "SQLite not found yet ($SqlitePath)." -ForegroundColor DarkYellow
  Write-Host "Open ShelfPOS once, then re-run this script to set store ID." -ForegroundColor DarkYellow
}

$NodeExe = Join-Path $InstallDir 'node.exe'
$ScriptJs = Join-Path $InstallDir 'dist\index.js'
$BinPath = "`"$NodeExe`" `"$ScriptJs`""

Write-Host 'Registering Windows service...' -ForegroundColor Yellow
sc.exe stop $ServiceName 2>$null | Out-Null
sc.exe delete $ServiceName 2>$null | Out-Null
Start-Sleep -Seconds 1

sc.exe create $ServiceName binPath= $BinPath start= auto DisplayName= "ShelfPOS Sync" | Out-Null
sc.exe description $ServiceName "Pushes ShelfPOS SQLite changes to Supabase (one-way sync)" | Out-Null
sc.exe failure $ServiceName reset= 86400 actions= restart/60000/restart/60000/restart/60000 | Out-Null

Write-Host 'Starting sync service...' -ForegroundColor Yellow
sc.exe start $ServiceName | Out-Null
Start-Sleep -Seconds 2

$svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($svc -and $svc.Status -eq 'Running') {
  Write-Host ''
  Write-Host 'Done! Sync service is installed and running.' -ForegroundColor Green
  Write-Host "  POS database: $SqlitePath"
  Write-Host "  Sync config:  $(Join-Path $InstallDir 'sync.env')"
  Write-Host "  Store ID:     $StoreId"
} else {
  Write-Host ''
  Write-Host 'Install finished but sync service is not running. Check Event Viewer or run:' -ForegroundColor Red
  Write-Host "  sc.exe query $ServiceName"
  Write-Host "  & `"$NodeExe`" `"$ScriptJs`"   # run in foreground to see errors"
  exit 1
}
