#Requires -RunAsAdministrator
<#
.SYNOPSIS
  Installs ShelfPOS (Electron) + background Supabase sync service on Windows.

.DESCRIPTION
  Run from the release bundle folder (right-click → Run with PowerShell as Administrator).
  1. Runs the ShelfPOS NSIS installer
  2. Copies sync-service to Program Files
  3. Writes sync.env with Supabase credentials
  4. Registers and starts the "ShelfPOS Sync" Windows service

.PARAMETER SupabaseUrl
  e.g. https://xxxx.supabase.co

.PARAMETER SupabaseServiceKey
  Service role key (Project Settings → API). NOT the anon key.

.PARAMETER StoreId
  store_a or store_b — stamped on every row pushed to Supabase.

.PARAMETER SkipPosInstall
  Skip running the NSIS installer (POS already installed).
#>
param(
  [string]$SupabaseUrl,
  [string]$SupabaseServiceKey,
  [string]$StoreId = 'store_a',
  [switch]$SkipPosInstall
)

$ErrorActionPreference = 'Stop'
$BundleRoot = $PSScriptRoot
$ServiceName = 'ShelfPOSSync'
$InstallDir = Join-Path ${env:ProgramFiles} 'ShelfPOS\sync-service'
$SqlitePath = Join-Path $env:APPDATA 'shelfpos\shelf.db'

function Prompt-Required([string]$Label, [switch]$Secret) {
  if ($Secret) {
    $secure = Read-Host $Label -AsSecureString
    return [Runtime.InteropServices.Marshal]::PtrToStringAuto(
      [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    )
  }
  return Read-Host $Label
}

Write-Host ''
Write-Host '=== ShelfPOS installer (POS + Supabase sync) ===' -ForegroundColor Cyan
Write-Host ''

if (-not $SupabaseUrl) {
  $SupabaseUrl = Prompt-Required 'Supabase URL (https://xxx.supabase.co)'
}
if (-not $SupabaseServiceKey) {
  $SupabaseServiceKey = Prompt-Required 'Supabase service role key' -Secret
}
$StoreId = ($StoreId).Trim()
if ($StoreId -notmatch '^store_[a-z0-9_]+$') {
  throw "Invalid StoreId: $StoreId (use store_a, store_b, etc.)"
}

$SetupExe = Get-ChildItem -Path $BundleRoot -Filter 'ShelfPOS Setup*.exe' -ErrorAction SilentlyContinue |
  Select-Object -First 1
if (-not $SetupExe -and -not $SkipPosInstall) {
  throw "ShelfPOS Setup*.exe not found in $BundleRoot"
}

$SyncSource = Join-Path $BundleRoot 'sync-service'
if (-not (Test-Path (Join-Path $SyncSource 'dist\index.js'))) {
  throw "sync-service bundle missing. Re-run npm run release:win on the build machine."
}

# --- 1. POS app (NSIS) ---
if (-not $SkipPosInstall) {
  Write-Host "Installing ShelfPOS app: $($SetupExe.Name)" -ForegroundColor Yellow
  $proc = Start-Process -FilePath $SetupExe.FullName -Wait -PassThru
  if ($proc.ExitCode -ne 0) {
    throw "ShelfPOS installer exited with code $($proc.ExitCode)"
  }
  Write-Host 'ShelfPOS app installed.' -ForegroundColor Green
} else {
  Write-Host 'Skipping POS installer (-SkipPosInstall).' -ForegroundColor DarkYellow
}

# --- 2. Sync service files ---
Write-Host "Installing sync service to $InstallDir" -ForegroundColor Yellow
if (Test-Path $InstallDir) {
  Stop-Service -Name $ServiceName -ErrorAction SilentlyContinue
  Start-Sleep -Seconds 1
  Remove-Item -Recurse -Force $InstallDir
}
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null

Copy-Item -Recurse -Force (Join-Path $SyncSource 'dist') (Join-Path $InstallDir 'dist')
Copy-Item -Recurse -Force (Join-Path $SyncSource 'node_modules') (Join-Path $InstallDir 'node_modules')
Copy-Item -Force (Join-Path $SyncSource 'package.json') $InstallDir
Copy-Item -Force (Join-Path $SyncSource 'node.exe') $InstallDir
Copy-Item -Recurse -Force (Join-Path $SyncSource 'scripts') (Join-Path $InstallDir 'scripts')

$SyncEnv = @"
# ShelfPOS sync service — auto-generated by Install-ShelfPOS.ps1
SUPABASE_URL=$SupabaseUrl
SUPABASE_SERVICE_KEY=$SupabaseServiceKey
SQLITE_PATH=$SqlitePath
"@
Set-Content -Path (Join-Path $InstallDir 'sync.env') -Value $SyncEnv -Encoding UTF8

# --- 3. store_id in SQLite (create DB dir if POS not opened yet) ---
$dbDir = Split-Path $SqlitePath -Parent
if (-not (Test-Path $dbDir)) {
  New-Item -ItemType Directory -Path $dbDir -Force | Out-Null
}
if (Test-Path $SqlitePath) {
  Write-Host "Setting sync_store_id=$StoreId in SQLite" -ForegroundColor Yellow
  & (Join-Path $InstallDir 'node.exe') `
    (Join-Path $InstallDir 'scripts\set-store-id.cjs') `
    $SqlitePath $StoreId
} else {
  Write-Host "SQLite not found yet ($SqlitePath). sync_store_id defaults to store_a on first POS launch." -ForegroundColor DarkYellow
  Write-Host "After first POS run, re-run: node scripts\set-store-id.cjs `"$SqlitePath`" $StoreId" -ForegroundColor DarkYellow
}

# --- 4. Windows service (sc.exe — no Node required on customer machine beyond bundled node.exe) ---
$NodeExe = Join-Path $InstallDir 'node.exe'
$ScriptJs = Join-Path $InstallDir 'dist\index.js'
$BinPath = "`"$NodeExe`" `"$ScriptJs`""

Write-Host 'Registering Windows service...' -ForegroundColor Yellow
sc.exe stop $ServiceName 2>$null | Out-Null
sc.exe delete $ServiceName 2>$null | Out-Null
Start-Sleep -Seconds 1

sc.exe create $ServiceName binPath= $BinPath start= auto DisplayName= "ShelfPOS Sync" | Out-Null
sc.exe description $ServiceName "Pushes ShelfPOS SQLite changes to Supabase (one-way sync)" | Out-Null
sc.exe failure $ServiceName reset= 86400 actions= restart/60000/restart/60000/restart/60000 | Out-Null

Write-Host 'Starting sync service...' -ForegroundColor Yellow
sc.exe start $ServiceName | Out-Null
Start-Sleep -Seconds 2

$svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($svc -and $svc.Status -eq 'Running') {
  Write-Host ''
  Write-Host 'Done! ShelfPOS + sync service are installed and running.' -ForegroundColor Green
  Write-Host "  POS database: $SqlitePath"
  Write-Host "  Sync config:  $(Join-Path $InstallDir 'sync.env')"
  Write-Host "  Store ID:     $StoreId"
} else {
  Write-Host ''
  Write-Host 'Install finished but sync service is not running. Check Event Viewer or run:' -ForegroundColor Red
  Write-Host "  sc.exe query $ServiceName"
  Write-Host "  & `"$NodeExe`" `"$ScriptJs`"   # run in foreground to see errors"
  exit 1
}
