/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppMovementsRouteImport } from './routes/_app/movements'
import { Route as AppLinkPosRouteImport } from './routes/_app/link-pos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCierresRouteImport } from './routes/_app/cierres'
import { Route as AppAuditRouteImport } from './routes/_app/audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLinkPosRoute = AppLinkPosRouteImport.update({
  id: '/link-pos',
  path: '/link-pos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCierresRoute = AppCierresRouteImport.update({
  id: '/cierres',
  path: '/cierres',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/cierres': typeof AppCierresRoute
  '/dashboard': typeof AppDashboardRoute
  '/link-pos': typeof AppLinkPosRoute
  '/movements': typeof AppMovementsRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/cierres': typeof AppCierresRoute
  '/dashboard': typeof AppDashboardRoute
  '/link-pos': typeof AppLinkPosRoute
  '/movements': typeof AppMovementsRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/cierres': typeof AppCierresRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/link-pos': typeof AppLinkPosRoute
  '/_app/movements': typeof AppMovementsRoute
  '/_app/reports': typeof AppReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/cierres'
    | '/dashboard'
    | '/link-pos'
    | '/movements'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/cierres'
    | '/dashboard'
    | '/link-pos'
    | '/movements'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/cierres'
    | '/_app/dashboard'
    | '/_app/link-pos'
    | '/_app/movements'
    | '/_app/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/movements': {
      id: '/_app/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/link-pos': {
      id: '/_app/link-pos'
      path: '/link-pos'
      fullPath: '/link-pos'
      preLoaderRoute: typeof AppLinkPosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cierres': {
      id: '/_app/cierres'
      path: '/cierres'
      fullPath: '/cierres'
      preLoaderRoute: typeof AppCierresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCierresRoute: typeof AppCierresRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLinkPosRoute: typeof AppLinkPosRoute
  AppMovementsRoute: typeof AppMovementsRoute
  AppReportsRoute: typeof AppReportsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCierresRoute: AppCierresRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLinkPosRoute: AppLinkPosRoute,
  AppMovementsRoute: AppMovementsRoute,
  AppReportsRoute: AppReportsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
